---
title: "In Class Ex 04"
description: |

author:
  - name: XiaoQi
    affiliation: School of Computing and Information Systems (SMU)
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.retina = 3) #default is 1
```
y
# Getting Started

## Setting up R packages

To start with, [ggstatplot](https://indrajeetpatil.github.io/ggstatsplot/) and tidyverse packages will be launched using `library()`.

```{r}
packages = c('ggstatsplot','tidyverse')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
}
```

## Importing Data

```{r}
exam <- read_csv("data/Exam_data.csv")

```
## Working with ggstatplot

###ANOVA Test

```{r}
ggbetweenstats(
  data = exam,
  x = RACE, 
  y = ENGLISH,
  type = "p",
  mean.ci = TRUE, 
  pairwise.comparisons = TRUE, 
  pairwise.display = "s",
  p.adjust.method = "fdr",
  messages = FALSE
)
```

```{r,  fig.width=6,fig.height=8}
set.seed(1234)

ggbetweenstats(
  data = exam,
  x = RACE, 
  y = ENGLISH,
  type = "nonparametric")
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
